# This is a basic workflow to help you get started with Actions

name: CI-MAIN

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ source ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: |
             npm ci
      - run: npm run build
      - run: ./resources/publish.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: version
        run: |
          git checkout -f -b version-branch
          npm version patch -m "$(git log -1 --pretty=%B) .... bump version [skip ci]"
          git push origin version-branch:source --follow-tags   
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: build site docker
        run: |
          echo "Before running 'npm run docker' , package ver is: ${npm_package_version}"
          docker login --username yehiyam --password ${DOCKER_HUB_PASS}
          PRIVATE_REGISTRY=docker.io/hkube npm run 
          export IMAGE_NAME=$(cat imageName.txt)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME: $IMAGE_NAME"
        env:
          DOCKER_HUB_PASS: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Trivy vulnerability scanner on the docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}'
          severity: CRITICAL
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif' 

      - name: trigger site docker
        id: trigger
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/kube-HPC/release-manager/dispatches
          event_type: trigger
        env:
          GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}'          

      