# This is a basic workflow to help you get started with Actions

name: CI-MAIN

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ deploy_a_docker ]

  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: version
        run: |
          git checkout -f -b version-branch
          npm version patch -m "$(git log -1 --pretty=%B) .... bump version [skip ci]"
          git push origin version-branch:deploy_a_docker --follow-tags   
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm ci
      - run: npm run build
      - run: ./resources/publish.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: build site docker
        run: |
          docker login --username yehiyam --password ${DOCKER_HUB_PASS}
          PRIVATE_REGISTRY=docker.io/hkube npm run docker
        env:
          DOCKER_HUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
      - name: trigger site docker
        id: trigger
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/kube-HPC/release-manager/dispatches
          event_type: trigger
          #client_payload: "{ \"placeholder\": \"placeholder\" }"
        env:
          GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}'          

      