# This is a basic workflow to help you get started with Actions

name: TRIVY-TEST

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ trivy* ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: |
             npm ci
      - run: |
             npm run trivy-test
             export IMAGE_NAME=$(cat imageName.txt)
             echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
             echo "IMAGE_NAME: $IMAGE_NAME"
             echo "env.IMAGE_NAME: ${{ env.IMAGE_NAME }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run Trivy vulnerability scanner on the docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      