# This is a basic workflow to help you get started with Actions

name: TRIVY-SCAN

# Controls when the action will run. 
on:
  push:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
    inputs:
      image-ref:
        description: Full docker image path (e.g. docker.io/hkube/site:v1.2.3)
        required: true
        default: 'docker.io/hkube/site:v2.6.4'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan_and_upload"
  scan_and_upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.43.0_Linux-64bit.deb
      
      - name: Run Trivy license scan on repo
        run: trivy fs /home/runner/work --scanners license --license-full --severity 'HIGH,CRITICAL' > trivy_license_filesystem.txt  
      
      - name: Run Trivy vulnerability scanner on repo
        run: trivy fs /home/runner/work --severity 'HIGH,CRITICAL' > trivy_vuln_filesystem.txt

      - name: Run Trivy license scan on image
        run: trivy image --scanners license --license-full --severity 'HIGH,CRITICAL' 'docker.io/hkube/site:v2.6.4' > trivy_license_image.txt

      - name: Run Trivy vulnerability scanner on image
        run: trivy image --severity 'HIGH,CRITICAL' 'docker.io/hkube/site:v2.6.4' > trivy_vuln_image.txt

      - name: Create branch for scan results
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          if git rev-parse --verify trivy-scan-results; then
            git checkout trivy-scan-results
          else
            git checkout -b trivy-scan-results
          fi

          mkdir -p TrivyScans
          cp trivy_license_filesystem.txt TrivyScans/
          cp trivy_vuln_filesystem.txt TrivyScans/
          cp trivy_license_image.txt TrivyScans/
          cp trivy_vuln_image.txt TrivyScans/
          git add TrivyScans/trivy_license_filesystem.txt
          git add TrivyScans/trivy_vuln_filesystem.txt
          git add TrivyScans/trivy_license_image.txt
          git add TrivyScans/trivy_vuln_image.txt
          git commit -m "Add trivy scan result files to the folder 'TrivyScans'"
          git push origin HEAD:trivy-scan-results

      - name: Display branch and file path link
        run: echo "Results uploaded to [trivy-scan-results branch](https://github.com/$GITHUB_REPOSITORY/tree/trivy-scan-results/TrivyScans/)"
      