name: Update Download Files from hkubectl Release

# Trigger the workflow when a new release is published in the hkubectl repository
on:
  repository_dispatch:
    types: [hkubectl-release]

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kube-HPC.github.io repository
        uses: actions/checkout@v2
        with:
          repository: kube-HPC/kube-HPC.github.io
          ref: source

      - name: Download latest release files from hkubectl
        run: |
          export latestVersion=$(curl -s https://api.github.com/repos/kube-HPC/hkubectl/releases/latest | jq -r .tag_name)
          mkdir -p site/hkubectl_files
          curl -L https://github.com/kube-HPC/hkubectl/releases/download/${latestVersion}/hkubectl-linux -o hkubectl_files/hkubectl-linux
          curl -L https://github.com/kube-HPC/hkubectl/releases/download/${latestVersion}/hkubectl-macos -o hkubectl_files/hkubectl-macos
          curl -L https://github.com/kube-HPC/hkubectl/releases/download/${latestVersion}/hkubectl-win.exe -o hkubectl_files/hkubectl-win.exe

      - name: Commit and push updated files to kube-HPC.github.io
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add hkubectl_files/*
          git commit -m "Update hkubectl download files to the latest release" || echo "No changes to commit"
          git push origin main
